version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - '5432:5432'
    volumes:
      - drkiq-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - drkiq-redis:/var/lib/redis/data

  drkiq:
    build:
      context: .
    image: abdelrahmankha/drkiq:1.0
    volumes:
      - ./drkiq:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    environment:
      SECRET_TOKEN: ${SECRET_TOKEN}
      WORKER_PROCESSES: ${WORKER_PROCESSES}
      LISTEN_ON: ${LISTEN_ON}
      DATABASE_URL: ${DATABASE_URL}
      CACHE_URL: ${CACHE_URL}
      JOB_WORKER_URL: ${JOB_WORKER_URL}

  sidekiq:
    build:
      context: .
    image: abdelrahmankha/sidekiq:1.0
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    environment:
      SECRET_TOKEN: ${SECRET_TOKEN}
      WORKER_PROCESSES: ${WORKER_PROCESSES}
      LISTEN_ON: ${LISTEN_ON}
      DATABASE_URL: ${DATABASE_URL}
      CACHE_URL: ${CACHE_URL}
      JOB_WORKER_URL: ${JOB_WORKER_URL}

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    image: abdelrahmankha/nginx:1.0
    links:
      - drkiq
    ports:
      - '8020:8020'

volumes:
  drkiq-postgres:
  drkiq-redis:
