apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
spec:
  containers:
  - name: postgres
    image: postgres:14.2
    volumeMounts:
    - name: db
      mountPath: /var/lib/postgresql/data
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: app-sec
          key: POSTGRES_USER

    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-sec
          key: POSTGRES_PASSWORD

    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          name: app-conf
          key: POSTGRES_DB
  volumes:
  - name: db
    hostPath:
      path: /var/pg_db
