apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod

spec:
  containers:
  - name: redis
    image: redis:7.0
    volumeMounts:
    - name: rdis-db
      mountPath: /var/lib/redis/data
    ports:
    - containerPort: 6379
    
  volumes:
  - name: rdis-db
    hostPath:
      path: /var/redis_db
